CP317-W2018-G3-master/subby/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings

from .views import application, user, sublet, account, rating, favourite, report

app_name = 'subby'

urlpatterns = [

    # Base application view
    path('', application.index, name='index'),

    # User Admin views
    path('users/', user.index, name='user_index'),
    path('users/<int:user_id>', user.show, name='user_show'),
    path('users/<int:user_id>/sublets', user.sublets, name='user_sublets'),
    path('users/<int:user_id>/lock_account', user.lock_account, name='user_lock_account'),

    # User session views
    path('login/', user.login, name='login'),
    path('logout/', user.logout, name='logout'),
    path('signup/', user.signup, name='signup'),
    # url(r'^auth/', include('social_django.urls', namespace='social')),


    # Account Paths
    path('account/', account.account_home, name='account_home'),
    path('account/update', account.update_user_info, name='update_user_info'),

    # Sublet paths
    path('sublets/', sublet.SubletList.as_view(template_name='sublet/sublet_list.html'), name='SubletList'),
    path('sublets/<int:pk>/', sublet.SubletDetail.as_view(template_name='sublet/sublet_detail.html'), name='SubletDetail'),
    path('sublets/create_sublet', sublet.create_sublet, name='create_sublet'),
    path('sublets/search', sublet.search, name='search'),
    path('sublets/contact', user.contact_user, name='contact_user'),
    path('sublets/update_sublet', sublet.update_sublet, name='update_sublet'),
    path('sublets/my_sublets', sublet.my_sublets, name='my_sublets'),
    path('sublets/my_sublets/delete_sublet/<int:sublet_id>', sublet.delete_sublet, name='delete_sublet'),

    # Rating paths

    path('ratings/<int:user_id>', rating.list_user_rating, name='RatingList'),
    path('ratings/write_review/', rating.write_review, name='write_review'),
    path('ratings/update_review/', rating.update_review, name='update_review'),
    path('ratings/reviews/<int:pk>/', rating.my_review, name='my_review'),
    path('ratings/delete/<int:rating_id>/<int:reviewed_user_id>/', rating.delete_review, name='delete_review'),

    # Favourite paths
    path('favourites/', favourite.FavouriteLister, name='favourite_list'),
    path('favourites/fav_unfav_sublet/', favourite.fav_unfav_sublet, name='fav_unfav_sublet'),
    path('favourites/unfav_sublet/<int:fav_id>', favourite.unfav_sublet, name='unfav_sublet'),
    path('favourites/favourite_bar_lister', favourite.favourite_bar_lister, name='favourite_bar_lister'),

    # Report paths
    path('report/<int:user_id>/<int:sublet_id>/', report.create_report, name='create_report'),
    path('report_list/', report.report_list, name='report_list'),
    path('search_report/', report.search_report, name='search_report'),

]

CP317-W2018-G3-master/subby/models/favourite.py
from django.db import models
from django.conf import settings
from subby.models.sublet import Sublet
from subby.managers.favouritesmanager import FavouriteManager

class Favourite(models.Model):

    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    sublet = models.ForeignKey(Sublet, on_delete=models.CASCADE)

    objects = FavouriteManager()

    def __str__(self):
       return self.sublet.get_sublet_title

    # Getters
    def get_favourite_id(self):
       return self.id;
	   
    def get_sublet_id(self):
       return self.sublet.id
	   
    def get_user_id(self):
       return self.user.id
	   
    def get_created_at(self):
       return self.created_at
	   
    def get_updated_at(self):
       return self.updated_at


    # Setters
	   
    def set_updated_at(self):
       self.updated_at = pytz.utc.localize(datetime.datetime.now())
       return

CP317-W2018-G3-master/subby/models/image.py
from django.db import models
from django.conf import settings
from subby.models.sublet import Sublet

class SubletImage(models.Model):
	sublet = models.ForeignKey(Sublet, related_name='sublet_image', on_delete=models.CASCADE)
	image = models.ImageField(upload_to='image/')

CP317-W2018-G3-master/subby/models/rating.py
from django.db import models
from django.conf import settings
from subby.managers.ratingmanager import RatingManager

import datetime, pytz
from . import User


ALLOWED_REVIEW_VALS = [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]

class Rating(models.Model):

    rating = models.FloatField()
    comment = models.CharField(max_length = 250, blank = True, null = True)
    user_id = models.PositiveIntegerField()
    reviewed_user_id = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    


    objects = RatingManager()

    def __str__(self):
        return "{} - {}".format(self.rating, self.comment)
    # Getters
    def get_rating(self):
        return self.rating
    def get_user_id(self):
        return self.user_id
    def get_reviewed_user_id(self):
        return self.reviewed_user_id
    def get_comment(self):
        return self.comment
    def get_created_at(self):
        return self.created_at
    def get_updated_at(self):
        return self.updated_at

    # Setters
    def set_rating(self, rating):
        self.rating = rating
        return

    def set_user_id(self, user_id):
        self.user_id = user_id
        return
    def set_reviewed_user_id(self, reviewed_user_id):
        self.reviewed_user_id = reviewed_user_id
        return
    def set_comment(self, comment):
        self.comment = comment
        return
    def set_created_at(self, created_at):
        self.created_at = created_at
        return
    def set_updated_at(self):
        self.updated_at = pytz.utc.localize(datetime.datetime.now())
        return

    # Helpers
    def validate_rating(self, rating):
        if rating in ALLOWED_REVIEW_VALS:
            return True
        else:
            return False
				
    class Meta:
       unique_together = ('user_id', 'reviewed_user_id')

CP317-W2018-G3-master/subby/views/account.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from subby.decorators.loginrequiredmessage import message_login_required
from subby.models.sublet import Sublet
from django.utils import timezone
from django.contrib.auth import get_user_model
User = get_user_model()

import datetime, pytz

@message_login_required
def account_home(request):
	id = request.user.id
	email = request.user.email
	first_name = request.user.first_name
	last_name = request.user.last_name
	created_at = request.user.created_at
	updated_at = request.user.updated_at
	phone_number = request.user.phone_number
	username = request.user.username
	
	user_dict = {
		'id' : id,
		'email': email,
		'first_name': first_name,
		'last_name': last_name,
		'created_at': created_at,
		'updated_at': updated_at,
		'phone_number': phone_number,
		'username': username,
	}
	return render(request, 'users/account_home.html', user_dict)

@message_login_required
def update_user_info(request):
	if request.method == 'POST':
			user = User.objects.get(email=request.user.email)
			user.first_name = request.POST['first']
			user.last_name = request.POST['last']
			user.phone_number = request.POST['phone']
			user.updated_at = pytz.utc.localize(datetime.datetime.now())
			user.save()
			return redirect('subby:account_home')
	else:
		#User wants to enter info
		return render(request, 'application/base.html')

CP317-W2018-G3-master/subby/views/application.py
from django.shortcuts import render
from django.http import HttpResponse
from django.conf import settings
from subby.models.image import SubletImage
# Create your views here.

def index(req):
    images = SubletImage.objects.all()
    return render(req, 'application/base.html', {'images' : images})

CP317-W2018-G3-master/subby/views/favourite.py
from django.shortcuts import render, get_object_or_404,redirect
from subby.models.favourite import Favourite
from subby.models.sublet import Sublet
from subby.models.image import SubletImage
from subby.decorators.loginrequiredmessage import message_login_required
from django.contrib import messages



	
@message_login_required
def FavouriteLister(request):
	fav_list = Favourite.objects.filter(user=request.user)
	
	image_dict = {}
	image_list = []
	for fav in fav_list:
		images = SubletImage.objects.filter(sublet=fav.sublet)
		if (len(images) > 0):
			image_list.append(images[0])
	fav_dict = {
		'fav_list':fav_list,
		'image_list':image_list,
	}
	return render(request, 'favourite/favourite_list.html', fav_dict)
    



@message_login_required
def favourite_bar_lister(request):
    fav_list = Favourite.objects.filter(user=request.user)

    image_list = []
    for fav in fav_list:
        images = SubletImage.objects.filter(sublet=fav.sublet)
        image_list.append(images[0])

    data = {
             'fav_list': fav_list,
             'image_list': image_list,
            }

    return render(request, 'favourite/favourite_nav.html', data)

# Favourites a sublet if not favourited, unfavourites a sublet if already favourited (deletes it from db)
def fav_unfav_sublet(request):

    current_user = request.user
    next = request.POST.get('next', '/')
    # Check if sublet exists
    try:
        sublet = get_object_or_404(Sublet, id=request.POST['subletid'])
    except(KeyError, Sublet.DoesNotExist):
        #return redirect('subby:SubletDetail', {'sublet': sublet, 'error': "Sublet does not exist."})
        return redirect(next, id=sublet.get_sublet_id())
    else:
        #If it exists check to see if this favourite already exists
        if(Favourite.objects.filter(user=current_user, sublet=sublet).count() > 0): #Remove favourite
            messages.add_message(request, messages.INFO, 'You have disliked the sublet')
            Favourite.objects.remove_favourite(sublet, current_user)
        else: #Add favourite
            messages.add_message(request, messages.INFO, 'You have liked the sublet')

            Favourite.objects.create_favourite(sublet, current_user)
        
        return redirect(next, id=sublet.get_sublet_id())


def unfav_sublet(request, fav_id):
	
	Favourite.objects.remove_by_id(fav_id)
	return redirect('subby:favourite_list')

CP317-W2018-G3-master/subby/views/rating.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
from django.urls import reverse

from subby.decorators.loginrequiredmessage import message_login_required
from subby.models.rating import Rating

User = get_user_model()


def list_user_rating(request, user_id):
    ratings = Rating.objects.filter(reviewed_user_id=user_id)
    lister = User.objects.get(id=user_id)
    raters = []
    posted = False
    reviewed_user_id = user_id

    total_rating = 0
    total_count = len(ratings)
    print(total_count)
    for rating in ratings:
        rater = User.objects.get(id=rating.user_id)
        raters.append(rater.email)
        total_rating += rating.rating

    if request.user.is_anonymous:
        current = None
        current_id = None
    else:
        current = request.user.email
        current_id = request.user.id
        for rater in raters:
            if rater == current:
                posted = True

    
    if total_count != 0:
        avg = total_rating / total_count
        avg_detail = format(avg, '.2f')
        avg = round(avg * 2) / 2
    else:
        avg = 0
        avg_detail = 0
    rating_dict = {
        'ratings': ratings,
        'raters': raters,
        'lister': lister,
        'current': current,
        'avg_rating': avg,
        'avg_detail': avg_detail,
        'posted': posted,
        'current_id': current_id,
        'reviewed_user_id': reviewed_user_id
    }
    return render(request, 'rating/rating_list.html', rating_dict)


@message_login_required
def write_review(request):
    if request.method == 'POST':
        current = request.user.email
        if request.POST['rating'] and request.POST['comment']:
            Rating.objects.create_rating(float(request.POST['rating']), request.POST['comment'], request.user.id,
                                         request.POST['reviewedid'])
            messages.add_message(request, messages.SUCCESS, "You have successfully left your review!")
            return redirect('subby:RatingList', request.POST['reviewedid'])
        else:
            messages.add_message(request, messages.ERROR, "All fields must be filled in to write a review")
            return redirect('subby:RatingList', request.POST['reviewedid'])


@message_login_required
def update_review(request):
    if request.method == 'POST':
        rating = Rating.objects.get(id=request.POST['ratingid'])
        if request.POST.get('rating'):
            if float(request.POST['rating']) != rating.rating:
                rating.set_rating(float(request.POST['rating']))
                rating.set_updated_at()
            if request.POST['comment'] != rating.comment:
                rating.set_comment(request.POST['comment'])
            rating.save()
            messages.add_message(request, messages.SUCCESS, "You have successfully updated your review!")
            return redirect(reverse('subby:RatingList', kwargs={'user_id': rating.reviewed_user_id}))
        else:
            messages.add_message(request, messages.ERROR, "Rating must be updated to edit review.")
            return redirect(reverse('subby:RatingList', kwargs={'user_id': rating.reviewed_user_id}))


@message_login_required
def my_review(request, pk):
    rating = Rating.objects.filter(reviewed_user_id=pk, user_id=request.user.id)
    print(rating[0].rating)
    return render(request, 'rating/rating_detail.html', {'rating': rating[0], 'lister': request.user})


@message_login_required
def delete_review(request, rating_id, reviewed_user_id):
    Rating.objects.filter(id=rating_id).delete()

    return redirect('subby:RatingList', user_id=reviewed_user_id)

CP317-W2018-G3-master/subby/views/report.py
import difflib

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect

from subby.decorators.loginrequiredmessage import message_login_required
from subby.models.report import Report
from subby.models.sublet import Sublet

User = get_user_model()


@message_login_required
def create_report(request, user_id, sublet_id):
    if request.method == 'POST':
        if request.POST.get('issue', None) and request.POST['description']:
            user = User.objects.get(id=user_id)
            sublet = Sublet.objects.get(id=sublet_id)

            Report.objects.create_report(user=user,
                                         sublet=sublet,
                                         issue=request.POST['issue'],
                                         description=request.POST['description'],
                                         )
            messages.add_message(request, messages.SUCCESS, 'You have successfully left a report.')
            return redirect('subby:SubletDetail', sublet_id)
        else:
            messages.add_message(request, messages.ERROR, 'All fields must be checked/filled in.')
            return redirect('subby:SubletDetail', sublet_id)

    report_dict = {
        'user_id': user_id,
        'sublet_id': sublet_id,
    }
    return render(request, 'report/report_page.html', report_dict)


def report_list(request):
    reports = Report.objects.all()
    return render(request, "report/report_list.html", {'reports': reports})


def search_report(request):
    if request.method == 'POST':
        reports = Report.objects.all()
        if request.POST['query']:
            filtered_reports = []
            for r in reports:
                if difflib.SequenceMatcher(None, r.user.email, request.POST['query']).ratio() > 0.3:
                    filtered_reports.append(r)
            messages.add_message(request, messages.INFO, 'Total results: ' + str(len(filtered_reports)))
            return render(request, "report/report_list.html", {'reports': filtered_reports})
        else:
            return render(request, "report/report_list.html", {'reports': reports})

CP317-W2018-G3-master/subby/templates/users/account_home.html
{% extends 'application/base.html' %}
{% block content %}

<div class="container">
	
	<div class="jumbotron jumbo-container">
		<div class="container">
			<h1 class="display-4">Account Home</h1>
			<a class="btn btn-secondary" href="{% url 'subby:create_sublet' %}">Post Sublet</a>
			
			<!-- <a class="btn btn-secondary" href="{% url 'subby:SubletList' %}">View All Posts</a> -->
			<a class="btn btn-secondary" href="{% url 'subby:my_sublets' %}">My Postings</a>
			<a class="btn btn-secondary" href="{% url 'subby:RatingList' user_id=id%}">View My Ratings</a>
			
			
			
			<a class="btn btn-secondary" href="{% url 'subby:favourite_list' %}">View Favourites</a>
			
			<hr class="my-4">
			<form action="{% url 'subby:update_user_info' %}" method="POST">
				{% csrf_token %}
				<fieldset class="edit-disabled-fieldset" disabled>
					<div class="form-group">
						<label for="account-page-email">Email:</label>
						<input type="email" id="account-page-email" name="email" class="form-control"
						placeholder="Email"
						value="{{ email }}" disabled>
					</div>
					<div class="form-group">
						<label for="account-page-username">Username:</label>
						<input type="username" id="account-page-username" name="username" class="form-control"
						placeholder="Username"
						value="{{ username }}" disabled>
					</div>
					<div class="form-group">
						<label for="account-page-fn">First Name:</label>
						<input type="text" id="account-page-fn" name="first" class="form-control"
						placeholder="First Name"
						value="{{ first_name }}">
					</div>
					<div class="form-group">
						<label for="account-page-ln">Last Name:</label>
						<input type="text" id="account-page-ln" name="last" class="form-control"
						placeholder="Last Name"
						value="{{ last_name }}">
					</div>
					<div class="form-group">
						<label for="account-page-pn">Phone Number:</label>
						<input type="text" id="account-page-pn" name="phone" class="form-control"
						placeholder="Phone Number"
						value="{{ phone_number }}">
					</div>
				</fieldset>
				<fieldset class="perm-disabled-fieldset" disabled>
					<div class="form-group">
						<label for="account-page-creation">Creation Date:</label>
						<input type="text" id="account-page-creation" class="form-control"
						placeholder="Creation Date"
						value="{{ created_at }}">
					</div>
					<div class="form-group">
						<label for="account-page-updated">Last Updated:</label>
						<input type="text" id="account-page-updated" class="form-control" placeholder="Last Updated"
						value="{{ updated_at }}">
					</div>
				</fieldset>
				<button type="submit" class="btn btn-secondary acc-submit-btn" style="display: none;">Submit
					Changes
				</button>
				
			</form>
			<button type="button" class="btn btn-secondary edit-btn">Edit</button>
		</div>
	</div>
</div>

{% endblock %}

CP317-W2018-G3-master/subby/templates/users/index.html
{% extends 'application/base.html' %}

{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'css/users/users.css' %}"/>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="jumbotron jumbo-container" style="min-height: 90vh;">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <h2>User Administration</h2>
                    </div>
                    <div class="col-md-5 offset-md-3" id="user-search-form">
                        <form action="{% url 'subby:user_index' %}" method="GET">
                            <div class="form-group">
                                {% if query %}
                                    <input class="form-control" type="search" placeholder="{{ query }}" aria-label="User Filter" name="query">
                                {% else %}
                                    <input class="form-control" type="search" placeholder="Search" aria-label="User Filter" name="query">
                                {% endif %}

                                <button class="btn btn-secondary search-btn" id="user-search-button" type="submit">Search</button>

                                {% if query %}
                                    <a href="{% url 'subby:user_index' %}">
                                        <button class="btn btn-secondary search-btn" id="user-search-clear">Clear</button>
                                    </a>
                                {% endif %}
                            </div>
                        </form>
                    </div>
                </div>
                    {% if users %}
                        <div class="row">
                            <div class="col-md-4"><h5>Email</h5></div>
                            <div class="col-md-4"><h5>First Name</h5></div>
                            <div class="col-md-4"><h5>Last Name</h5></div>
                        </div>
                        {% for user in users %}
                            <div class="row user-row" onclick="window.location='{% url 'subby:user_show' user.id %}';">
                                <div class="col-md-4">
                                    <span>{{ user.email }}</span>
                                </div>
                                <div class="col-md-4">
                                    <span>{% if user.first_name != None %} {{ user.first_name }} {% else %} {% endif %}</span>
                                </div>
                                <div class="col-md-4">
                                    <span>{% if user.last_name != None %} {{ user.last_name }} {% else %} {% endif %}</span>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <h5>No users to show</h5>
                    {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

CP317-W2018-G3-master/subby/templates/users/login.html
<!-- temporary login page used for report prototype purpose -->

{% extends 'application/base.html' %}

{% block content %}
<div class="container">
{% if error %}
{{ error }}
<br /><br />

{% endif %}

<h1>Login</h1>

<form method="POST" action="{% url 'subby:login' %}">
	<!--whenever we use a form we have to use csrf_token to
		get protection from other attack-->
	{% csrf_token %}
	Username:<br />
	<input type="text" name="username"/><br />
	Password:<br />
	<input type="password" name="password" /><br /><br />
	<input class="btn btn-primary" type="submit" value="Login!" />

</form>

<br />

<h1 class="hello">Hello</h1>
</div>

{% endblock %}

CP317-W2018-G3-master/subby/templates/users/show.html
{% extends 'application/base.html' %}
{% block content %}

    <div class="container">

        <div class="jumbotron jumbo-container">
            <div class="container">
                <h1 class="display-4">User: {{ user.email }}</h1>
                <a class="btn btn-secondary" href="{% url 'subby:user_sublets' user_id=user.id %}">User Sublets</a>
                <a class="btn btn-secondary" href="{% url 'subby:RatingList' user_id=user.id %}">User Ratings</a>

                <hr class="my-4">

                <fieldset class="edit-disabled-fieldset" disabled>
                    <div class="form-group">
                        <label for="account-page-email">Email:</label>
                        <input type="email" id="account-page-email" name="email" class="form-control"
                                placeholder="Email"
                                value="{{ user.email }}">
                    </div>
                    <div class="form-group">
                        <label for="account-page-fn">First Name:</label>
                        <input type="text" id="account-page-fn" name="first" class="form-control"
                                placeholder="First Name"
                                value="{{ user.first_name }}">
                    </div>
                    <div class="form-group">
                        <label for="account-page-ln">Last Name:</label>
                        <input type="text" id="account-page-ln" name="last" class="form-control"
                                placeholder="Last Name"
                                value="{{ user.last_name }}">
                    </div>
                    <div class="form-group">
                        <label for="account-page-pn">Phone Number:</label>
                        <input type="text" id="account-page-pn" name="phone" class="form-control"
                                placeholder="Phone Number"
                                value="{{ user.phone_number }}">
                    </div>
                </fieldset>

                <fieldset class="perm-disabled-fieldset" disabled>
                    <div class="form-group">
                        <label for="account-page-creation">Creation Date:</label>
                        <input type="text" id="account-page-creation" class="form-control"
                                placeholder="Creation Date"
                                value="{{ user.created_at }}">
                    </div>
                    <div class="form-group">
                        <label for="account-page-updated">Last Updated:</label>
                        <input type="text" id="account-page-updated" class="form-control" placeholder="Last Updated"
                                value="{{ user.updated_at }}">
                    </div>
                </fieldset>

                {% csrf_token %}
                <button class="btn lock-account-btn {{ btn_class }}"
                    data-user-locked="{{ user.is_active }}"
                    data-lock-url="{% url 'subby:user_lock_account' user_id=user.id %}">
                    {{ btn_text }}
                </button>
            </div>
        </div>
    </div>

{% endblock %}

CP317-W2018-G3-master/subby/templates/users/signup.html
<!-- temporary signup page used for report prototype purpose -->

{% extends 'application/base.html' %}

{% block content %}
<div class="container">
{% if error %}
{{ error }}
<br /><br />

{% endif %}

<h1>Sign Up!</h1>

<form method="POST" action="{% url 'subby:signup' %}">
	<!--whenever we use a form we have to use csrf_token to
		get protection from other attack-->
	{% csrf_token %}
	Username:<br />
	<input type="text" name="username"/><br />
	Password:<br />
	<input type="password" name="password1" /><br />
	Confirm Password:<br />
	<input type="password" name="password2" /><br /><br />
	<input class="btn btn-primary" type="submit" value="Sign Up!" />

</form>
</div>

{% endblock %}

CP317-W2018-G3-master/subby/templates/users/sublets.html
{% extends 'application/base.html' %}

{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'css/users/sublets.css' %}"/>
{% endblock %}

{% block content %}

<div class="container">
  <div class="jumbotron jumbo-container" style="min-height: 90vh;">
    <div class="container">
      <h2>Sublet Postings for {{ user.email }}</h2>
      {% if user.sublets.all.count > 0 %}
        <br>
        {% for sublet in user.sublets.all %}
        <div class="container">
          <div class="row">
            <div class="col-md-3"><h5>Title</h5></div>
            <div class="col-md-5"><h5>Address</h5></div>
            <div class="col-md-3"><h5>Rent</h5></div>
          </div>
          <div class="row sublet-items" onclick="window.location='{% url 'subby:SubletDetail' sublet.id %}';" style="cursor:pointer;">
            <div class="col-md-3"><span>{{ sublet.title }}</span></div>
            <div class="col-md-5"><span>{{ sublet.street_address }}, {{ sublet.city }}</span></div>
            <div class="col-md-3"><span>${{ sublet.price }}</span></div>
          </div>
          <hr>
        </div>
        {% endfor %}
      {% else %}
        <p>This user has no sublet postings.</p>
      {% endif %}
      <br>
    </div>
  </div>
</div>

{% endblock %}