CP317-W2018-G3-master/subby/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings

from .views import application, user, sublet, account, rating, favourite, report

app_name = 'subby'

urlpatterns = [

    # Base application view
    path('', application.index, name='index'),

    # User Admin views
    path('users/', user.index, name='user_index'),
    path('users/<int:user_id>', user.show, name='user_show'),
    path('users/<int:user_id>/sublets', user.sublets, name='user_sublets'),
    path('users/<int:user_id>/lock_account', user.lock_account, name='user_lock_account'),

    # User session views
    path('login/', user.login, name='login'),
    path('logout/', user.logout, name='logout'),
    path('signup/', user.signup, name='signup'),
    # url(r'^auth/', include('social_django.urls', namespace='social')),


    # Account Paths
    path('account/', account.account_home, name='account_home'),
    path('account/update', account.update_user_info, name='update_user_info'),

    # Sublet paths
    path('sublets/', sublet.SubletList.as_view(template_name='sublet/sublet_list.html'), name='SubletList'),
    path('sublets/<int:pk>/', sublet.SubletDetail.as_view(template_name='sublet/sublet_detail.html'), name='SubletDetail'),
    path('sublets/create_sublet', sublet.create_sublet, name='create_sublet'),
    path('sublets/search', sublet.search, name='search'),
    path('sublets/contact', user.contact_user, name='contact_user'),
    path('sublets/update_sublet', sublet.update_sublet, name='update_sublet'),
    path('sublets/my_sublets', sublet.my_sublets, name='my_sublets'),
    path('sublets/my_sublets/delete_sublet/<int:sublet_id>', sublet.delete_sublet, name='delete_sublet'),

    # Rating paths

    path('ratings/<int:user_id>', rating.list_user_rating, name='RatingList'),
    path('ratings/write_review/', rating.write_review, name='write_review'),
    path('ratings/update_review/', rating.update_review, name='update_review'),
    path('ratings/reviews/<int:pk>/', rating.my_review, name='my_review'),
    path('ratings/delete/<int:rating_id>/<int:reviewed_user_id>/', rating.delete_review, name='delete_review'),

    # Favourite paths
    path('favourites/', favourite.FavouriteLister, name='favourite_list'),
    path('favourites/fav_unfav_sublet/', favourite.fav_unfav_sublet, name='fav_unfav_sublet'),
    path('favourites/unfav_sublet/<int:fav_id>', favourite.unfav_sublet, name='unfav_sublet'),
    path('favourites/favourite_bar_lister', favourite.favourite_bar_lister, name='favourite_bar_lister'),

    # Report paths
    path('report/<int:user_id>/<int:sublet_id>/', report.create_report, name='create_report'),
    path('report_list/', report.report_list, name='report_list'),
    path('search_report/', report.search_report, name='search_report'),

]

CP317-W2018-G3-master/subby/models/favourite.py
from django.db import models
from django.conf import settings
from subby.models.sublet import Sublet
from subby.managers.favouritesmanager import FavouriteManager

class Favourite(models.Model):

    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    sublet = models.ForeignKey(Sublet, on_delete=models.CASCADE)

    objects = FavouriteManager()

    def __str__(self):
       return self.sublet.get_sublet_title

    # Getters
    def get_favourite_id(self):
       return self.id;
	   
    def get_sublet_id(self):
       return self.sublet.id
	   
    def get_user_id(self):
       return self.user.id
	   
    def get_created_at(self):
       return self.created_at
	   
    def get_updated_at(self):
       return self.updated_at


    # Setters
	   
    def set_updated_at(self):
       self.updated_at = pytz.utc.localize(datetime.datetime.now())
       return

CP317-W2018-G3-master/subby/models/image.py
from django.db import models
from django.conf import settings
from subby.models.sublet import Sublet

class SubletImage(models.Model):
	sublet = models.ForeignKey(Sublet, related_name='sublet_image', on_delete=models.CASCADE)
	image = models.ImageField(upload_to='image/')

CP317-W2018-G3-master/subby/models/rating.py
from django.db import models
from django.conf import settings
from subby.managers.ratingmanager import RatingManager

import datetime, pytz
from . import User


ALLOWED_REVIEW_VALS = [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]

class Rating(models.Model):

    rating = models.FloatField()
    comment = models.CharField(max_length = 250, blank = True, null = True)
    user_id = models.PositiveIntegerField()
    reviewed_user_id = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    


    objects = RatingManager()

    def __str__(self):
        return "{} - {}".format(self.rating, self.comment)
    # Getters
    def get_rating(self):
        return self.rating
    def get_user_id(self):
        return self.user_id
    def get_reviewed_user_id(self):
        return self.reviewed_user_id
    def get_comment(self):
        return self.comment
    def get_created_at(self):
        return self.created_at
    def get_updated_at(self):
        return self.updated_at

    # Setters
    def set_rating(self, rating):
        self.rating = rating
        return

    def set_user_id(self, user_id):
        self.user_id = user_id
        return
    def set_reviewed_user_id(self, reviewed_user_id):
        self.reviewed_user_id = reviewed_user_id
        return
    def set_comment(self, comment):
        self.comment = comment
        return
    def set_created_at(self, created_at):
        self.created_at = created_at
        return
    def set_updated_at(self):
        self.updated_at = pytz.utc.localize(datetime.datetime.now())
        return

    # Helpers
    def validate_rating(self, rating):
        if rating in ALLOWED_REVIEW_VALS:
            return True
        else:
            return False
				
    class Meta:
       unique_together = ('user_id', 'reviewed_user_id')

CP317-W2018-G3-master/subby/views/account.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from subby.decorators.loginrequiredmessage import message_login_required
from subby.models.sublet import Sublet
from django.utils import timezone
from django.contrib.auth import get_user_model
User = get_user_model()

import datetime, pytz

@message_login_required
def account_home(request):
	id = request.user.id
	email = request.user.email
	first_name = request.user.first_name
	last_name = request.user.last_name
	created_at = request.user.created_at
	updated_at = request.user.updated_at
	phone_number = request.user.phone_number
	username = request.user.username
	
	user_dict = {
		'id' : id,
		'email': email,
		'first_name': first_name,
		'last_name': last_name,
		'created_at': created_at,
		'updated_at': updated_at,
		'phone_number': phone_number,
		'username': username,
	}
	return render(request, 'users/account_home.html', user_dict)

@message_login_required
def update_user_info(request):
	if request.method == 'POST':
			user = User.objects.get(email=request.user.email)
			user.first_name = request.POST['first']
			user.last_name = request.POST['last']
			user.phone_number = request.POST['phone']
			user.updated_at = pytz.utc.localize(datetime.datetime.now())
			user.save()
			return redirect('subby:account_home')
	else:
		#User wants to enter info
		return render(request, 'application/base.html')

CP317-W2018-G3-master/subby/views/application.py
from django.shortcuts import render
from django.http import HttpResponse
from django.conf import settings
from subby.models.image import SubletImage
# Create your views here.

def index(req):
    images = SubletImage.objects.all()
    return render(req, 'application/base.html', {'images' : images})

CP317-W2018-G3-master/subby/views/favourite.py
from django.shortcuts import render, get_object_or_404,redirect
from subby.models.favourite import Favourite
from subby.models.sublet import Sublet
from subby.models.image import SubletImage
from subby.decorators.loginrequiredmessage import message_login_required
from django.contrib import messages



	
@message_login_required
def FavouriteLister(request):
	fav_list = Favourite.objects.filter(user=request.user)
	
	image_dict = {}
	image_list = []
	for fav in fav_list:
		images = SubletImage.objects.filter(sublet=fav.sublet)
		if (len(images) > 0):
			image_list.append(images[0])
	fav_dict = {
		'fav_list':fav_list,
		'image_list':image_list,
	}
	return render(request, 'favourite/favourite_list.html', fav_dict)
    



@message_login_required
def favourite_bar_lister(request):
    fav_list = Favourite.objects.filter(user=request.user)

    image_list = []
    for fav in fav_list:
        images = SubletImage.objects.filter(sublet=fav.sublet)
        image_list.append(images[0])

    data = {
             'fav_list': fav_list,
             'image_list': image_list,
            }

    return render(request, 'favourite/favourite_nav.html', data)

# Favourites a sublet if not favourited, unfavourites a sublet if already favourited (deletes it from db)
def fav_unfav_sublet(request):

    current_user = request.user
    next = request.POST.get('next', '/')
    # Check if sublet exists
    try:
        sublet = get_object_or_404(Sublet, id=request.POST['subletid'])
    except(KeyError, Sublet.DoesNotExist):
        #return redirect('subby:SubletDetail', {'sublet': sublet, 'error': "Sublet does not exist."})
        return redirect(next, id=sublet.get_sublet_id())
    else:
        #If it exists check to see if this favourite already exists
        if(Favourite.objects.filter(user=current_user, sublet=sublet).count() > 0): #Remove favourite
            messages.add_message(request, messages.INFO, 'You have disliked the sublet')
            Favourite.objects.remove_favourite(sublet, current_user)
        else: #Add favourite
            messages.add_message(request, messages.INFO, 'You have liked the sublet')

            Favourite.objects.create_favourite(sublet, current_user)
        
        return redirect(next, id=sublet.get_sublet_id())


def unfav_sublet(request, fav_id):
	
	Favourite.objects.remove_by_id(fav_id)
	return redirect('subby:favourite_list')

CP317-W2018-G3-master/subby/views/rating.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
from django.urls import reverse

from subby.decorators.loginrequiredmessage import message_login_required
from subby.models.rating import Rating

User = get_user_model()


def list_user_rating(request, user_id):
    ratings = Rating.objects.filter(reviewed_user_id=user_id)
    lister = User.objects.get(id=user_id)
    raters = []
    posted = False
    reviewed_user_id = user_id

    total_rating = 0
    total_count = len(ratings)
    print(total_count)
    for rating in ratings:
        rater = User.objects.get(id=rating.user_id)
        raters.append(rater.email)
        total_rating += rating.rating

    if request.user.is_anonymous:
        current = None
        current_id = None
    else:
        current = request.user.email
        current_id = request.user.id
        for rater in raters:
            if rater == current:
                posted = True

    
    if total_count != 0:
        avg = total_rating / total_count
        avg_detail = format(avg, '.2f')
        avg = round(avg * 2) / 2
    else:
        avg = 0
        avg_detail = 0
    rating_dict = {
        'ratings': ratings,
        'raters': raters,
        'lister': lister,
        'current': current,
        'avg_rating': avg,
        'avg_detail': avg_detail,
        'posted': posted,
        'current_id': current_id,
        'reviewed_user_id': reviewed_user_id
    }
    return render(request, 'rating/rating_list.html', rating_dict)


@message_login_required
def write_review(request):
    if request.method == 'POST':
        current = request.user.email
        if request.POST['rating'] and request.POST['comment']:
            Rating.objects.create_rating(float(request.POST['rating']), request.POST['comment'], request.user.id,
                                         request.POST['reviewedid'])
            messages.add_message(request, messages.SUCCESS, "You have successfully left your review!")
            return redirect('subby:RatingList', request.POST['reviewedid'])
        else:
            messages.add_message(request, messages.ERROR, "All fields must be filled in to write a review")
            return redirect('subby:RatingList', request.POST['reviewedid'])


@message_login_required
def update_review(request):
    if request.method == 'POST':
        rating = Rating.objects.get(id=request.POST['ratingid'])
        if request.POST.get('rating'):
            if float(request.POST['rating']) != rating.rating:
                rating.set_rating(float(request.POST['rating']))
                rating.set_updated_at()
            if request.POST['comment'] != rating.comment:
                rating.set_comment(request.POST['comment'])
            rating.save()
            messages.add_message(request, messages.SUCCESS, "You have successfully updated your review!")
            return redirect(reverse('subby:RatingList', kwargs={'user_id': rating.reviewed_user_id}))
        else:
            messages.add_message(request, messages.ERROR, "Rating must be updated to edit review.")
            return redirect(reverse('subby:RatingList', kwargs={'user_id': rating.reviewed_user_id}))


@message_login_required
def my_review(request, pk):
    rating = Rating.objects.filter(reviewed_user_id=pk, user_id=request.user.id)
    print(rating[0].rating)
    return render(request, 'rating/rating_detail.html', {'rating': rating[0], 'lister': request.user})


@message_login_required
def delete_review(request, rating_id, reviewed_user_id):
    Rating.objects.filter(id=rating_id).delete()

    return redirect('subby:RatingList', user_id=reviewed_user_id)

CP317-W2018-G3-master/subby/views/report.py
import difflib

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect

from subby.decorators.loginrequiredmessage import message_login_required
from subby.models.report import Report
from subby.models.sublet import Sublet

User = get_user_model()


@message_login_required
def create_report(request, user_id, sublet_id):
    if request.method == 'POST':
        if request.POST.get('issue', None) and request.POST['description']:
            user = User.objects.get(id=user_id)
            sublet = Sublet.objects.get(id=sublet_id)

            Report.objects.create_report(user=user,
                                         sublet=sublet,
                                         issue=request.POST['issue'],
                                         description=request.POST['description'],
                                         )
            messages.add_message(request, messages.SUCCESS, 'You have successfully left a report.')
            return redirect('subby:SubletDetail', sublet_id)
        else:
            messages.add_message(request, messages.ERROR, 'All fields must be checked/filled in.')
            return redirect('subby:SubletDetail', sublet_id)

    report_dict = {
        'user_id': user_id,
        'sublet_id': sublet_id,
    }
    return render(request, 'report/report_page.html', report_dict)


def report_list(request):
    reports = Report.objects.all()
    return render(request, "report/report_list.html", {'reports': reports})


def search_report(request):
    if request.method == 'POST':
        reports = Report.objects.all()
        if request.POST['query']:
            filtered_reports = []
            for r in reports:
                if difflib.SequenceMatcher(None, r.user.email, request.POST['query']).ratio() > 0.3:
                    filtered_reports.append(r)
            messages.add_message(request, messages.INFO, 'Total results: ' + str(len(filtered_reports)))
            return render(request, "report/report_list.html", {'reports': filtered_reports})
        else:
            return render(request, "report/report_list.html", {'reports': reports})

CP317-W2018-G3-master/subby/templates/sublet/create_sublet.html
{% extends 'application/base.html' %}

{% block content %}
    <div class="container">
        <div class="jumbotron jumbo-container">
            <div class="container">
                <h1 class="display-4">Create a sublet listing</h1>
                <p class="lead">Enter the following information</p>
                <hr class="my-4">
                {% if create_sublet_error %}
                    <div class="alert alert-danger fade show" role="alert" id="error-container" style="height:120px;">
                        <h4 class="alert-heading">Error</h4>
                        <p>{{ create_sublet_error }}</p>
                        <button type="button" class="close" onclick="$('.alert').hide()" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}

                <form method="POST" action="{% url 'subby:create_sublet' %} " enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="listing-title">Listing Name:</label>
                        <input type="text" class="form-control" id="listing-title" name="title"
                               aria-describedby="Listing Name" placeholder="Enter Listing Name" data-toggle="popover" data-content="Please enter a title">
                        <label class="mt-2" for="listing-duration">Listing Duration (months):</label>
                        <input type="number" class="form-control" id="listing-duration" name="duration"
                               aria-describedby="Listing Duration" min="1" max="12" value="1" data-toggle="popover" data-content="Please enter a duration">
                        <br>
                        <label for="pac-input">Search an address:</label>
                        <input id="pac-input" class="controls form-control" type="text"
                               placeholder="Enter Address" autocomplete="off" data-toggle="popover" data-content="Enter a valid address"/><br/>
                        <div id="map" style="height: 250px;"></div>
                        <div id="infowindow-content">
                            <img src="" width="16" height="16" id="place-icon">
                            <span id="place-name" class="title"></span><br>
                            <span id="place-address"></span>
                        </div>
                        <label for="street_address">Street Address:</label>
                        <input type="text" class="form-control" name="street_address" id="street_address"
                               aria-describedby="Street Address" placeholder="Enter Address">
                        <label class="mt-2" for="city">City:</label>
                        <input type="text" class="form-control" name="city" id="city"
                               aria-describedby="City Name" placeholder="Enter City Name (Waterloo or Kitchener)" data-toggle="popover" data-content="City has to be Waterloo or Kitchener">
                        <label class="mt-2" for="postal_code">Postal Code:</label>
                        <input type="text" class="form-control" name="postal_code" id="postal_code"
                               aria-describedby="Postal Code" placeholder="Enter Postal Code">
                        <label class="mt-2" for="price">Price/Month:</label>
                        <input type="text" class="form-control" name="price" id="price"
                               aria-describedby="Price" placeholder="Enter Listing Price" data-toggle="popover" data-content="Please enter a price">
                        <label class="mt-2" for="listing-description">Description:</label>
                        <textarea class="form-control" name="description" id="listing-description"
                                  aria-describedby="Description" placeholder="Please enter a description as detailed as possible, including furnitures, nearby facilitates, bus routes, beg/end of the sublet, etc." rows="10" data-toggle="popover" data-content="Please enter a description."></textarea>
                        <label class="mt-2" for="image-upload">Upload Images:</label>
                        <input type="file" class="form-control" id="files" name="files" multiple
                               aria-describedby="Image Upload" data-toggle="popover" data-content="Upload some images">
                        <label class="mt-2" for="image-list">Previews:</label>
                        <output class="form-control" id="image-list" style="min-height: 100px; height: auto;"></output>

                        <input type="hidden" class="form-control" name="lat" id="lat"
                               aria-describedby="Latitude" placeholder="Enter Latitude">

                        <input type="hidden" class="form-control" name="lng" id="lng"
                               aria-describedby="Longitude" placeholder="Enter Longitude">

                        <input type="submit" id="create-sublet-submit" class="btn btn-primary d-block mr-0 mt-3 float-right" value="Create"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
            integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
            crossorigin="anonymous"></script>
    {% load static %}

    <script src="{% static 'js/FileHandling.js' %}"></script>
    <script src="{% static 'js/CreateSubletVerification.js' %}"></script>
    <script src="{% static 'js/MapAPI.js' %}"></script>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCWKqqOWg7D2pCCKgsGe_ISDMUyEkkxXzY&libraries=places&callback=init_map"
            async defer></script>
			

{% endblock %}

CP317-W2018-G3-master/subby/templates/sublet/my_sublets.html
{% extends 'application/base.html' %}

{% block content %}

<div class="container">
	<div class="jumbotron jumbo-container" style="min-height: 90vh;">
		<div class="container">
			<h2>My Postings List</h2>
			{% if my_postings|length > 0 %}
			<br>
			{% for post in my_postings %}
			<div class="container">
				<div class="row">
					<div class="col-md-3">
						<div onclick="window.location='{% url 'subby:SubletDetail' post.id %}';" style="cursor:pointer;">
							<h4 id="sublet_title">{{ post.title }}</h4>
							{% for i in image_list %}
							{% if i.sublet.id == post.id %}
							<img src="{{ i.image.url }}" class="img-fluid" height="200"
							width="200"/>
							{% endif %}
							{% endfor %}
						</div>
					</div>
					<div class="col-md-3 mt-1">
						<h5>Address</h5>
						<p>{{ post.street_address }}, {{ post.city }}</p>
						<h5>Rent</h5>
						<p>${{ post.price }}</p>
					</div>
					<div class="col-md-2 mt-1">
						<h5>Description</h5>
						<p>{{ post.summary }}</p>
						<h5>Offered By</h5>
						<p style="color:green;">{{ post.user.username }}</p>
					</div>
					<div class="col-md-1 mt-1">
						<button class="btn btn-danger float-right mr-2" type="button"
						data-toggle="modal" data-target="#delete-modal"
						aria-controls="deletingToggler" aria-expanded="false"
						aria-label="Toggle navigation">Delete
						</button>
					</div>
					
				</div>
				<hr>
			</div>
			<div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="delete-modal-label"
			aria-hidden="true">
				<div class="modal-dialog" role="document">
					<div class="modal-content bg-dark">
						<div class="modal-header">
							<div>
								<h4 class="text-white">Delete the sublet?</h4>
								
							</div>
						</div>
						<form method="POST" action="{% url 'subby:delete_sublet' sublet_id=post.id%}">
							{% csrf_token %}
							
							<div class="modal-footer">
								<button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
								
								<button type="submit" class="btn btn-primary" id="submit_button">Yes</button>
								
							</div>
						</form>
					</div>
				</div>
			</div>
			{% endfor %}
			{% else %}
			<p>You have no posting yet. <a class="btn btn-secondary" href="{% url 'subby:create_sublet' %}">Post a Sublet?</a></p>
			
			{% endif %}
			<br>
			
		</div>
	</div>
</div>



{% endblock %}

CP317-W2018-G3-master/subby/templates/sublet/search_sublets.html
{% extends 'application/base.html' %}

{% block content %}
<div class="jumbotron jumbo-container">
	<div class="container-fluid search-sublet-main-container">
		<div class="row">
			<div class="col-7">
				<div class="fav-bar">{% include "favourite/favourite_bar.html" %}</div>
				<div class="container-fluid search-container">
					<h2>
                        Search Results: {{ place.count }} results found
					</h2>
                    <button type="button" data-toggle="collapse" data-target="#filterToggler"
					class="btn btn-secondary btn-sm" aria-controls="filterToggler" aria-expanded="false"
					aria-label="Toggle navigation">
                        Advanced filters
					</button>
					
                    <div class="collapse" id="filterToggler">
                        <div class="bg-dark p-4 mt-2" style="border-radius: 5px;">
                            <h6 class="text-white">Advanced Filters</h6>
                            <form action="{% url 'subby:search' %}" method="POST">
                                {% csrf_token %}
                                <div class="form-group text-light">
                                    <input type="hidden" name="lat" value="{{ lat }}">
                                    <input type="hidden" name="lng" value="{{ lng }}">
                                    <label for="prox">Proximity within(km):</label>
                                    <input class="form-control" name="proximity" id="prox" type="number" min="1"
									value="{{ prox }}">
                                    <label for="duration">Duration (months):</label>
                                    <input class="form-control" name="duration" id="duration" type="number" min="1" max="12"
									value="{{ duration }}">
									<label for="price">price (<=):</label>
										<input class="form-control" name="price" id="price" type="number" value="{{ price }}">
										<button class="btn btn-secondary btn-sm mt-3" type="submit">Filter</button>
									</div>
									</form>
								</div>
							</div>
							<br><br>

					<div id="main-page"> <!-- Everything contained within this will be animated by Favourite nav bar opening/closing -->
							{% for p in place %}
							<div class="card gallery" style="width: 12rem;cursor:pointer;" id="sublet{{ p.id }}" onclick="window.location='{% url 'subby:SubletDetail' p.id %}';">
								<!-- {% load index %} -->
								<img class="card-img-top" src="{{ cover|index:forloop.counter0 }}" alt="">
								<div class="card-body" >
									<h6 class="card-title">{{ p.title }}, For {{ p.duration }} months</h6>
									<p class="card-title">{{ p.street_address }} </p>
									<h6 class="card-title">{{ p.city }}, ${{ p.price}}</h6>
									<h6 class="card-title">Created at: {{ p.pub_date_pretty }}</h6>
									<br />
								</div>
								
							</div>

							{% endfor %}
						</div>
			</div> <!-- End of "main-page" -->
					</div>
					<div class="col-5">
						<div id="map" style="min-height: 100%; height: auto;"></div>
					</div>
				</div>
			</div>
		</div>
		{% endblock %}
		
		{% block js %}
		<script>
			function init_searchmap() {
				
				let myOptions = {
					center: new google.maps.LatLng({{ lat }}, {{ lng }}),
					zoom: 13,
					mapTypeId: google.maps.MapTypeId.ROADMAP
					
				};
				let map = new google.maps.Map(document.getElementById("map"),
				myOptions);
				let bounds = new google.maps.LatLngBounds();
				setMarkers(map, bounds)
				
			}
			
			
			function setMarkers(map, bounds) {
				
				{%  for p in place %}
				latlngset = new google.maps.LatLng({{ p.latitude }}, {{ p.longitude }});
				marker = new google.maps.Marker({
					map: map, title: '{{ p.title }}', position: latlngset
				});
				map.setCenter(marker.getPosition());
				
				content = "Listing Name: <a href='{% url 'subby:SubletDetail' p.id %}'>{{ p.title }}</a>" + '<br>' + "Address: {{ p.street_address }}" + '<br>' + " City: {{ p.city }}" + '<br>' +
				'Price: ${{ p.price }}/mo';
				
				infowindow = new google.maps.InfoWindow();
				
				google.maps.event.addListener(marker, 'click', (function (marker, content, infowindow) {
					return function () {
						var sublet = document.getElementById('sublet{{ p.id }}');
						{% for p in place %}
						document.getElementById('sublet{{p.id}}').style.backgroundColor = 'white';
						{% endfor %}
						sublet.style.backgroundColor = 'lightblue';
						window.location.href="#sublet{{ p.id }}";
						infowindow.setContent(content);
						infowindow.open(map, marker);
						
					};
				})(marker, content, infowindow));
				
				bounds.extend(marker.getPosition());
				
				map.fitBounds(bounds);
				{% endfor %}
				
			}
		</script>
		
		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCWKqqOWg7D2pCCKgsGe_ISDMUyEkkxXzY&libraries=places&callback=init_searchmap"
		async defer></script>
	{% endblock %}	