CP317-W2018-G3-master/subby/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings

from .views import application, user, sublet, account, rating, favourite, report

app_name = 'subby'

urlpatterns = [

    # Base application view
    path('', application.index, name='index'),

    # User Admin views
    path('users/', user.index, name='user_index'),
    path('users/<int:user_id>', user.show, name='user_show'),
    path('users/<int:user_id>/sublets', user.sublets, name='user_sublets'),
    path('users/<int:user_id>/lock_account', user.lock_account, name='user_lock_account'),

    # User session views
    path('login/', user.login, name='login'),
    path('logout/', user.logout, name='logout'),
    path('signup/', user.signup, name='signup'),
    # url(r'^auth/', include('social_django.urls', namespace='social')),


    # Account Paths
    path('account/', account.account_home, name='account_home'),
    path('account/update', account.update_user_info, name='update_user_info'),

    # Sublet paths
    path('sublets/', sublet.SubletList.as_view(template_name='sublet/sublet_list.html'), name='SubletList'),
    path('sublets/<int:pk>/', sublet.SubletDetail.as_view(template_name='sublet/sublet_detail.html'), name='SubletDetail'),
    path('sublets/create_sublet', sublet.create_sublet, name='create_sublet'),
    path('sublets/search', sublet.search, name='search'),
    path('sublets/contact', user.contact_user, name='contact_user'),
    path('sublets/update_sublet', sublet.update_sublet, name='update_sublet'),
    path('sublets/my_sublets', sublet.my_sublets, name='my_sublets'),
    path('sublets/my_sublets/delete_sublet/<int:sublet_id>', sublet.delete_sublet, name='delete_sublet'),

    # Rating paths

    path('ratings/<int:user_id>', rating.list_user_rating, name='RatingList'),
    path('ratings/write_review/', rating.write_review, name='write_review'),
    path('ratings/update_review/', rating.update_review, name='update_review'),
    path('ratings/reviews/<int:pk>/', rating.my_review, name='my_review'),
    path('ratings/delete/<int:rating_id>/<int:reviewed_user_id>/', rating.delete_review, name='delete_review'),

    # Favourite paths
    path('favourites/', favourite.FavouriteLister, name='favourite_list'),
    path('favourites/fav_unfav_sublet/', favourite.fav_unfav_sublet, name='fav_unfav_sublet'),
    path('favourites/unfav_sublet/<int:fav_id>', favourite.unfav_sublet, name='unfav_sublet'),
    path('favourites/favourite_bar_lister', favourite.favourite_bar_lister, name='favourite_bar_lister'),

    # Report paths
    path('report/<int:user_id>/<int:sublet_id>/', report.create_report, name='create_report'),
    path('report_list/', report.report_list, name='report_list'),
    path('search_report/', report.search_report, name='search_report'),

]

CP317-W2018-G3-master/subby/models/favourite.py
from django.db import models
from django.conf import settings
from subby.models.sublet import Sublet
from subby.managers.favouritesmanager import FavouriteManager

class Favourite(models.Model):

    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    sublet = models.ForeignKey(Sublet, on_delete=models.CASCADE)

    objects = FavouriteManager()

    def __str__(self):
       return self.sublet.get_sublet_title

    # Getters
    def get_favourite_id(self):
       return self.id;
	   
    def get_sublet_id(self):
       return self.sublet.id
	   
    def get_user_id(self):
       return self.user.id
	   
    def get_created_at(self):
       return self.created_at
	   
    def get_updated_at(self):
       return self.updated_at


    # Setters
	   
    def set_updated_at(self):
       self.updated_at = pytz.utc.localize(datetime.datetime.now())
       return

CP317-W2018-G3-master/subby/models/image.py
from django.db import models
from django.conf import settings
from subby.models.sublet import Sublet

class SubletImage(models.Model):
	sublet = models.ForeignKey(Sublet, related_name='sublet_image', on_delete=models.CASCADE)
	image = models.ImageField(upload_to='image/')

CP317-W2018-G3-master/subby/models/rating.py
from django.db import models
from django.conf import settings
from subby.managers.ratingmanager import RatingManager

import datetime, pytz
from . import User


ALLOWED_REVIEW_VALS = [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]

class Rating(models.Model):

    rating = models.FloatField()
    comment = models.CharField(max_length = 250, blank = True, null = True)
    user_id = models.PositiveIntegerField()
    reviewed_user_id = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    


    objects = RatingManager()

    def __str__(self):
        return "{} - {}".format(self.rating, self.comment)
    # Getters
    def get_rating(self):
        return self.rating
    def get_user_id(self):
        return self.user_id
    def get_reviewed_user_id(self):
        return self.reviewed_user_id
    def get_comment(self):
        return self.comment
    def get_created_at(self):
        return self.created_at
    def get_updated_at(self):
        return self.updated_at

    # Setters
    def set_rating(self, rating):
        self.rating = rating
        return

    def set_user_id(self, user_id):
        self.user_id = user_id
        return
    def set_reviewed_user_id(self, reviewed_user_id):
        self.reviewed_user_id = reviewed_user_id
        return
    def set_comment(self, comment):
        self.comment = comment
        return
    def set_created_at(self, created_at):
        self.created_at = created_at
        return
    def set_updated_at(self):
        self.updated_at = pytz.utc.localize(datetime.datetime.now())
        return

    # Helpers
    def validate_rating(self, rating):
        if rating in ALLOWED_REVIEW_VALS:
            return True
        else:
            return False
				
    class Meta:
       unique_together = ('user_id', 'reviewed_user_id')

CP317-W2018-G3-master/subby/views/account.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from subby.decorators.loginrequiredmessage import message_login_required
from subby.models.sublet import Sublet
from django.utils import timezone
from django.contrib.auth import get_user_model
User = get_user_model()

import datetime, pytz

@message_login_required
def account_home(request):
	id = request.user.id
	email = request.user.email
	first_name = request.user.first_name
	last_name = request.user.last_name
	created_at = request.user.created_at
	updated_at = request.user.updated_at
	phone_number = request.user.phone_number
	username = request.user.username
	
	user_dict = {
		'id' : id,
		'email': email,
		'first_name': first_name,
		'last_name': last_name,
		'created_at': created_at,
		'updated_at': updated_at,
		'phone_number': phone_number,
		'username': username,
	}
	return render(request, 'users/account_home.html', user_dict)

@message_login_required
def update_user_info(request):
	if request.method == 'POST':
			user = User.objects.get(email=request.user.email)
			user.first_name = request.POST['first']
			user.last_name = request.POST['last']
			user.phone_number = request.POST['phone']
			user.updated_at = pytz.utc.localize(datetime.datetime.now())
			user.save()
			return redirect('subby:account_home')
	else:
		#User wants to enter info
		return render(request, 'application/base.html')

CP317-W2018-G3-master/subby/views/application.py
from django.shortcuts import render
from django.http import HttpResponse
from django.conf import settings
from subby.models.image import SubletImage
# Create your views here.

def index(req):
    images = SubletImage.objects.all()
    return render(req, 'application/base.html', {'images' : images})

CP317-W2018-G3-master/subby/views/favourite.py
from django.shortcuts import render, get_object_or_404,redirect
from subby.models.favourite import Favourite
from subby.models.sublet import Sublet
from subby.models.image import SubletImage
from subby.decorators.loginrequiredmessage import message_login_required
from django.contrib import messages



	
@message_login_required
def FavouriteLister(request):
	fav_list = Favourite.objects.filter(user=request.user)
	
	image_dict = {}
	image_list = []
	for fav in fav_list:
		images = SubletImage.objects.filter(sublet=fav.sublet)
		if (len(images) > 0):
			image_list.append(images[0])
	fav_dict = {
		'fav_list':fav_list,
		'image_list':image_list,
	}
	return render(request, 'favourite/favourite_list.html', fav_dict)
    



@message_login_required
def favourite_bar_lister(request):
    fav_list = Favourite.objects.filter(user=request.user)

    image_list = []
    for fav in fav_list:
        images = SubletImage.objects.filter(sublet=fav.sublet)
        image_list.append(images[0])

    data = {
             'fav_list': fav_list,
             'image_list': image_list,
            }

    return render(request, 'favourite/favourite_nav.html', data)

# Favourites a sublet if not favourited, unfavourites a sublet if already favourited (deletes it from db)
def fav_unfav_sublet(request):

    current_user = request.user
    next = request.POST.get('next', '/')
    # Check if sublet exists
    try:
        sublet = get_object_or_404(Sublet, id=request.POST['subletid'])
    except(KeyError, Sublet.DoesNotExist):
        #return redirect('subby:SubletDetail', {'sublet': sublet, 'error': "Sublet does not exist."})
        return redirect(next, id=sublet.get_sublet_id())
    else:
        #If it exists check to see if this favourite already exists
        if(Favourite.objects.filter(user=current_user, sublet=sublet).count() > 0): #Remove favourite
            messages.add_message(request, messages.INFO, 'You have disliked the sublet')
            Favourite.objects.remove_favourite(sublet, current_user)
        else: #Add favourite
            messages.add_message(request, messages.INFO, 'You have liked the sublet')

            Favourite.objects.create_favourite(sublet, current_user)
        
        return redirect(next, id=sublet.get_sublet_id())


def unfav_sublet(request, fav_id):
	
	Favourite.objects.remove_by_id(fav_id)
	return redirect('subby:favourite_list')

CP317-W2018-G3-master/subby/views/rating.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
from django.urls import reverse

from subby.decorators.loginrequiredmessage import message_login_required
from subby.models.rating import Rating

User = get_user_model()


def list_user_rating(request, user_id):
    ratings = Rating.objects.filter(reviewed_user_id=user_id)
    lister = User.objects.get(id=user_id)
    raters = []
    posted = False
    reviewed_user_id = user_id

    total_rating = 0
    total_count = len(ratings)
    print(total_count)
    for rating in ratings:
        rater = User.objects.get(id=rating.user_id)
        raters.append(rater.email)
        total_rating += rating.rating

    if request.user.is_anonymous:
        current = None
        current_id = None
    else:
        current = request.user.email
        current_id = request.user.id
        for rater in raters:
            if rater == current:
                posted = True

    
    if total_count != 0:
        avg = total_rating / total_count
        avg_detail = format(avg, '.2f')
        avg = round(avg * 2) / 2
    else:
        avg = 0
        avg_detail = 0
    rating_dict = {
        'ratings': ratings,
        'raters': raters,
        'lister': lister,
        'current': current,
        'avg_rating': avg,
        'avg_detail': avg_detail,
        'posted': posted,
        'current_id': current_id,
        'reviewed_user_id': reviewed_user_id
    }
    return render(request, 'rating/rating_list.html', rating_dict)


@message_login_required
def write_review(request):
    if request.method == 'POST':
        current = request.user.email
        if request.POST['rating'] and request.POST['comment']:
            Rating.objects.create_rating(float(request.POST['rating']), request.POST['comment'], request.user.id,
                                         request.POST['reviewedid'])
            messages.add_message(request, messages.SUCCESS, "You have successfully left your review!")
            return redirect('subby:RatingList', request.POST['reviewedid'])
        else:
            messages.add_message(request, messages.ERROR, "All fields must be filled in to write a review")
            return redirect('subby:RatingList', request.POST['reviewedid'])


@message_login_required
def update_review(request):
    if request.method == 'POST':
        rating = Rating.objects.get(id=request.POST['ratingid'])
        if request.POST.get('rating'):
            if float(request.POST['rating']) != rating.rating:
                rating.set_rating(float(request.POST['rating']))
                rating.set_updated_at()
            if request.POST['comment'] != rating.comment:
                rating.set_comment(request.POST['comment'])
            rating.save()
            messages.add_message(request, messages.SUCCESS, "You have successfully updated your review!")
            return redirect(reverse('subby:RatingList', kwargs={'user_id': rating.reviewed_user_id}))
        else:
            messages.add_message(request, messages.ERROR, "Rating must be updated to edit review.")
            return redirect(reverse('subby:RatingList', kwargs={'user_id': rating.reviewed_user_id}))


@message_login_required
def my_review(request, pk):
    rating = Rating.objects.filter(reviewed_user_id=pk, user_id=request.user.id)
    print(rating[0].rating)
    return render(request, 'rating/rating_detail.html', {'rating': rating[0], 'lister': request.user})


@message_login_required
def delete_review(request, rating_id, reviewed_user_id):
    Rating.objects.filter(id=rating_id).delete()

    return redirect('subby:RatingList', user_id=reviewed_user_id)

CP317-W2018-G3-master/subby/views/report.py
import difflib

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect

from subby.decorators.loginrequiredmessage import message_login_required
from subby.models.report import Report
from subby.models.sublet import Sublet

User = get_user_model()


@message_login_required
def create_report(request, user_id, sublet_id):
    if request.method == 'POST':
        if request.POST.get('issue', None) and request.POST['description']:
            user = User.objects.get(id=user_id)
            sublet = Sublet.objects.get(id=sublet_id)

            Report.objects.create_report(user=user,
                                         sublet=sublet,
                                         issue=request.POST['issue'],
                                         description=request.POST['description'],
                                         )
            messages.add_message(request, messages.SUCCESS, 'You have successfully left a report.')
            return redirect('subby:SubletDetail', sublet_id)
        else:
            messages.add_message(request, messages.ERROR, 'All fields must be checked/filled in.')
            return redirect('subby:SubletDetail', sublet_id)

    report_dict = {
        'user_id': user_id,
        'sublet_id': sublet_id,
    }
    return render(request, 'report/report_page.html', report_dict)


def report_list(request):
    reports = Report.objects.all()
    return render(request, "report/report_list.html", {'reports': reports})


def search_report(request):
    if request.method == 'POST':
        reports = Report.objects.all()
        if request.POST['query']:
            filtered_reports = []
            for r in reports:
                if difflib.SequenceMatcher(None, r.user.email, request.POST['query']).ratio() > 0.3:
                    filtered_reports.append(r)
            messages.add_message(request, messages.INFO, 'Total results: ' + str(len(filtered_reports)))
            return render(request, "report/report_list.html", {'reports': filtered_reports})
        else:
            return render(request, "report/report_list.html", {'reports': reports})

CP317-W2018-G3-master/subby/templates/rating/rating_detail.html
{% extends 'application/base.html' %}


{% block content %}
{% load staticfiles %}
<div class="container">
	<div class="jumbotron jumbo-container" style="min-height: 90vh; max-height: 90vh; overflow-y: scroll;">
		
		<h2 class="hello" >Your review for {{ lister.username }} 
			<a class="btn btn-secondary float-right" href="{% url 'subby:RatingList' user_id=rating.reviewed_user_id %}">View All Reviews
			</a>
		</h2><br />
		
		<div class="container bg-dark rounded text-light">
			<div class="row">
				<div class="col mt-1">
					<h5 class="mt-3">
						<input class="btn btn-secondary float-right" type="button"
						data-toggle="collapse" data-target="#editToggler{{ rating.id }}"
						aria-controls="editToggler" aria-expanded="false"
						aria-label="Toggle navigation" value="Edit" id="edit_button" onclick="edit_fold()">
						</input>
					</h5>
					
					<button class="btn btn-danger float-right mr-2" type="button"
					data-toggle="modal" data-target="#delete-modal"
					aria-controls="deletingToggler" aria-expanded="false"
					aria-label="Toggle navigation">Delete
					</button>
					<!-- <button id="myBtn" class="btn btn-danger float-right mr-2">Delete</button> -->

					
					<fieldset class="rating float-left" disabled>
						{% if rating.rating == 5 %}
						<input type="radio" id="5s" value="5" checked/>
						{% else %}
						<input type="radio" id="5s" value="5"/>
						{% endif %}
						<label class="full" for="5s" title="Perfect - 5 stars"></label>
						{% if rating.rating == 4.5 %}
						<input type="radio" id="4p5s" value="4.5" checked/>
						{% else %}
						<input type="radio" id="4p5s" value="4.5"/>
						{% endif %}
						
						<label class="half" for="4p5s" title="Great - 4.5 stars"></label>
						{% if rating.rating == 4 %}
						<input type="radio" id="4s" value="4" checked/>
						{% else %}
						<input type="radio" id="4s" value="4"/>
						{% endif %}
						
						<label class="full" for="4s" title="Good - 4 stars"></label>
						{% if rating.rating == 3.5 %}
						<input type="radio" id="3p5s" value="3.5" checked/>
						{% else %}
						<input type="radio" id="3p5s" value="3.5"/>
						{% endif %}
						
						<label class="half" for="3p5s" title="Satisfactory - 3.5 stars"></label>
						{% if rating.rating == 3 %}
						<input type="radio" id="3s" value="3" checked/>
						{% else %}
						<input type="radio" id="3s" value="3"/>
						{% endif %}
						
						<label class="full" for="3s" title="Average - 3 stars"></label>
						{% if rating.rating == 2.5 %}
						<input type="radio" id="2p5s" value="2.5" checked/>
						{% else %}
						<input type="radio" id="2p5s" value="2.5"/>
						{% endif %}
						
						<label class="half" for="2p5s" title="Okay - 2.5 stars"></label>
						{% if rating.rating == 2 %}
						<input type="radio" id="2s" value="2" checked/>
						{% else %}
						<input type="radio" id="2s" value="2"/>
						{% endif %}
						
						<label class="full" for="2s" title="Not good - 2 stars"></label>
						{% if rating.rating == 1.5 %}
						<input type="radio" id="1p5s" value="1.5" checked/>
						{% else %}
						<input type="radio" id="1p5s" value="1.5"/>
						{% endif %}
						
						<label class="half" for="1p5s" title="Bad - 1.5 stars"></label>
						{% if rating.rating == 1 %}
						<input type="radio" id="1s" value="1" checked/>
						{% else %}
						<input type="radio" id="1s" value="1"/>
						{% endif %}
						
						<label class="full" for="1s" title="Terrible - 1 star"></label>
						{% if rating.rating == 0.5 %}
						<input type="radio" id="p5s" value="0.5" checked/>
						{% else %}
						<input type="radio" id="p5s" value="0.5"/>
						{% endif %}
						<label class="half" for="p5s" title="The Worst - 0.5 stars"></label>
					</fieldset>
				</div>
			</div>
			<div class="row">
				<div class="col">
					<h6>Comment:</h6>
					<p>{{ rating.comment }}</p>
				</div>
			</div>
			<div class="collapse" id="editToggler{{ rating.id }}">
				<div class="bg-dark p-4 mt-2" style="border-radius: 5px;">
					<h4 class="text-white" id="editToggler1{{ rating.id }}" >Edit Review</h4>
					<span class="text-muted">Edit your rating or comment below.</span>
					<hr class="my-4">
					<form action="{% url 'subby:update_review' %}" method="POST">
						{% csrf_token %}
						<div class="modal-body">
							<div class="form-group">
								<input type="hidden" name="ratingid" value="{{ rating.id }}">
								<input type="hidden" name="reviewedid" value="{{ lister.id }}">
								<div class="form-row">
									<fieldset class="rating" oninput="edit_detect_rating()">
										<input type="radio" id="b5s{{ rating.id }}" name="rating" value="5"/>
										<label class="full" for="b5s{{ rating.id }}" title="Perfect - 5 stars"></label>
										<input type="radio" id="b4p5s{{ rating.id }}" name="rating" value="4.5"/>
										<label class="half" for="b4p5s{{ rating.id }}" title="Great - 4.5 stars"></label>
										<input type="radio" id="b4s{{ rating.id }}" name="rating" value="4"/>
										<label class="full" for="b4s{{ rating.id }}" title="Good - 4 stars"></label>
										<input type="radio" id="b3p5s{{ rating.id }}" name="rating" value="3.5"/>
										<label class="half" for="b3p5s{{ rating.id }}"
										title="Satisfactory - 3.5 stars"></label>
										<input type="radio" id="b3s{{ rating.id }}" name="rating" value="3"/>
										<label class="full" for="b3s{{ rating.id }}" title="Average - 3 stars"></label>
										<input type="radio" id="b2p5s{{ rating.id }}" name="rating" value="2.5"/>
										<label class="half" for="b2p5s{{ rating.id }}" title="Okay - 2.5 stars"></label>
										<input type="radio" id="b2s{{ rating.id }}" name="rating" value="2"/>
										<label class="full" for="b2s{{ rating.id }}" title="Not good - 2 stars"></label>
										<input type="radio" id="b1p5s{{ rating.id }}" name="rating" value="1.5"/>
										<label class="half" for="b1p5s{{ rating.id }}" title="Bad - 1.5 stars"></label>
										<input type="radio" id="b1s{{ rating.id }}" name="rating" value="1"/>
										<label class="full" for="b1s{{ rating.id }}" title="Terrible - 1 star"></label>
										<input type="radio" id="bp5s{{ rating.id }}" name="rating" value="0.5"/>
										<label class="half" for="bp5s{{ rating.id }}"
										title="The Worst - 0.5 stars"></label>
									</fieldset>
								</div>
								<label class="text-light" for="comment{{ rating.id }}">Comment:</label>
								<textarea class="form-control" id="comment1" name="comment"
								placeholder="Comment about seller"
								rows="8" oninput="edit_detect_rating()" >{{ rating.comment }}</textarea>
								
								<button type="submit" class="btn btn-secondary mt-3" disabled id="save_button">Save</button>
							</div>
						</div>
					</form>
				</div>
			</div>
			<hr>
		</div>
	</div>
</div>

<div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="delete-modal-label"
aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content bg-dark">
			<div class="modal-header">
				<div>
					<h4 class="text-white">Delete the Review?</h4>
					
				</div>
			</div>
			<form method="POST" action="{% url 'subby:delete_review' rating_id=rating.id reviewed_user_id=rating.reviewed_user_id%}">
				{% csrf_token %}
				
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
					
					<button type="submit" class="btn btn-primary" id="submit_button">Yes</button>
					
				</div>
			</form>
		</div>
	</div>
</div>


{% endblock %}		


{% block js %}
<script>
	function edit_fold() {
		var edit_button = document.getElementById('edit_button');
		if (edit_button.value == "Edit"){
			edit_button.value = "Fold";
			}else {
			edit_button.value = "Edit";
		}
	}
</script>

<script>
	function edit_detect_rating(){
		var message = document.getElementById('comment1');
		var save_button = document.getElementById('save_button');
		if (message.value != ""){
			save_button.disabled = false;
			}else {
			save_button.disabled = true;
		}
	}
</script>

{% endblock %}